theme = "onedark"

[editor]
line-number = "relative"
true-color = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
G = "goto_file_end"
X = "extend_line_above"
ret = ["move_line_down", "goto_line_start"]

[keys.normal.q]
q = ":reflow"

[keys.normal.space]
q = ":quit"
w = ":write"

[editor.lsp]
display-messages = true
